# Generated by Django 2.2.9 on 2020-01-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
    ]
