# Generated by Django 2.2.9 on 2020-01-25 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='curratt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='humans.Teacher'),
        ),
        migrations.AlterField(
            model_name='group',
            name='headman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='humans.Student'),
        ),
    ]
