# Generated by Django 2.2.9 on 2020-01-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0002_remove_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
