# Generated by Django 2.2.9 on 2020-01-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0002_auto_20200125_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='humans.Group'),
        ),
    ]
