# Generated by Django 2.2.9 on 2020-01-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0003_teacher_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
