# Generated by Django 2.2.9 on 2020-01-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0003_student_group_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_num',
        ),
    ]
