# Generated by Django 2.2.9 on 2020-01-21 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0003_auto_20200111_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='curratt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cur', to='humans.Teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='headman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headm', to='humans.Group'),
        ),
    ]
