# Generated by Django 2.2.9 on 2020-01-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0004_remove_student_group_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groupp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='humans.Group'),
        ),
    ]
