# Generated by Django 2.2.9 on 2020-01-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0004_auto_20200121_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='curratt',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group',
        ),
    ]
