# Generated by Django 2.2.9 on 2020-01-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0005_auto_20200122_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='curator',
            new_name='curratt',
        ),
    ]
