# Generated by Django 2.2.9 on 2020-01-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0005_auto_20200123_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='phone',
        ),
    ]
