# Generated by Django 2.2.9 on 2020-01-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0006_auto_20200122_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
