# Generated by Django 2.2.9 on 2020-02-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0007_logger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='time_delta',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
    ]
