# Generated by Django 2.2.9 on 2020-02-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0008_auto_20200204_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='time_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
