# Generated by Django 2.2.9 on 2020-01-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0008_auto_20200122_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='curratt',
        ),
    ]
