# Generated by Django 2.2.9 on 2020-01-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0009_remove_group_curratt'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='curratt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cur', to='humans.Teacher'),
        ),
    ]
