# Generated by Django 2.2.9 on 2020-02-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0009_auto_20200204_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='time_delta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
